version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: apexa
      MYSQL_DATABASE: apexa
      MYSQL_USER: apexa
      MYSQL_PASSWORD: apexa
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3309"]
      interval: 10s
      timeout: 5s
      retries: 5

  