version: '3'

services:
  app:
    platform: linux/arm64
    build:
      context: ../..
      dockerfile: deployment/local/http/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../..:/app
    restart: unless-stopped
